version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  order_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
        - order_postgres_data:/var/lib/postgresql/data

  order_service:
    build: ./services/order_service
    environment:
      DATABASE_URL: postgresql://user:password@order_postgres:5432/orderdb
    ports:
      - "80:80"
    depends_on:
      - kafka
      - order_postgres

  inventory_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventorydb
    ports:
      - "5434:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

  inventory_service:
    build: ./services/inventory_service
    environment:
      DATABASE_URL: postgresql://user:password@inventory_postgres:5432/inventorydb
    ports:
      - "81:81"
    depends_on:
      - kafka
      - inventory_postgres

volumes:
  order_postgres_data:
  inventory_postgres_data: